import {images} from '../assets';
import type {PlaceItem} from '../domain/visitTypes';

export const places: PlaceItem[] = [
  {
    id: 'wascana-centre',
    title: 'Wascana Centre',
    tag: 'Nature',
    category: 'Nature',
    address: '2900 Wascana Drive, Regina, SK',
    coordinates: {latitude: 50.4358, longitude: -104.6044},
    image: images.places.wascanaCentre,
    description:
      'A large scenic park area built around Wascana Lake, with walking paths, open lawns, garden spaces, lake views, monuments, and peaceful outdoor scenery near the heart of Regina. It is one of the best places for a slower break before or after visiting the venue, especially for guests who want fresh air, soft views, and a calm walking route without leaving the city.',
    suggestedVisit: '2-3 hours',
    bestFor: 'Walking, lake views, outdoor photos, peaceful breaks, relaxed city exploring.',
    tip: 'Visit during daylight or early evening for the best lake atmosphere and photo-friendly views across the water.',
  },
  {
    id: 'victoria-park',
    title: 'Victoria Park',
    tag: 'Downtown Park',
    category: 'Nature',
    address: '12th Avenue & Scarth Street, Regina, SK',
    coordinates: {latitude: 50.4481, longitude: -104.6126},
    image: images.places.farmersMarket,
    description:
      'A central downtown park located within a short distance of the venue, offering green space, walking paths, public seating, monuments, and a classic city-centre atmosphere. It works well as a quick outdoor pause for guests who want to step away from indoor activity and enjoy a simple Regina downtown landmark.',
    suggestedVisit: '30-60 minutes',
    bestFor: 'Short walks, downtown breaks, quick photos, guests exploring nearby streets.',
    tip: 'This is a practical stop if you want something close, simple, and easy to visit without planning a long route.',
  },
  {
    id: 'royal-saskatchewan-museum',
    title: 'Royal Saskatchewan Museum',
    tag: 'Museum',
    category: 'Museums',
    address: '2445 Albert Street, Regina, SK',
    coordinates: {latitude: 50.4398, longitude: -104.6165},
    image: images.places.scienceCentre,
    description:
      'A well-known cultural stop focused on Saskatchewan natural history, wildlife, fossils, landscapes, and regional heritage. It is a strong choice for visitors who want a meaningful museum experience close to central Regina, with exhibits that feel informative but still easy to enjoy during a casual city visit.',
    suggestedVisit: '1.5-2 hours',
    bestFor: 'Museums, families, history, natural science, rainy-day visits.',
    tip: 'Pair this stop with Wascana Centre, because both can fit naturally into one relaxed route.',
  },
  {
    id: 'saskatchewan-legislative-building',
    title: 'Saskatchewan Legislative Building',
    tag: 'Landmark',
    category: 'Landmarks',
    address: '2405 Legislative Drive, Regina, SK',
    coordinates: {latitude: 50.4329, longitude: -104.6159},
    image: images.places.governmentHouse,
    description:
      'A major Regina landmark overlooking Wascana Lake, known for its impressive architecture, landscaped grounds, and strong connection to Saskatchewan public history. The building and surrounding area are ideal for guests who enjoy architecture, classic city views, and a more formal cultural stop during their visit.',
    suggestedVisit: '1-1.5 hours',
    bestFor: 'Architecture, city history, landmark photos, walking near Wascana Lake.',
    tip: 'The exterior grounds are especially good for photos, and the visit feels more complete when combined with a walk along Wascana Lake.',
  },
  {
    id: 'stone-hall-castle',
    title: 'Stone Hall Castle',
    tag: 'Historic Landmark',
    category: 'Landmarks',
    address: '2210 College Avenue, Regina, SK',
    coordinates: {latitude: 50.4426, longitude: -104.6155},
    image: images.onboardingAccess,
    description:
      'A distinctive castle-style attraction in Regina with historic character, detailed interiors, and a guided-tour atmosphere. It is a memorable nearby place for guests who want something more unusual than a standard museum or park, with a dramatic interior style that feels especially fitting for a premium city guide section.',
    suggestedVisit: '1.5 hours',
    bestFor: 'Unique interiors, guided tours, historic atmosphere, photo-friendly visits.',
    tip: 'Check tour availability before going, because this location is best experienced as a planned visit rather than a quick walk-in stop.',
  },
  {
    id: 'regina-farmers-market-area',
    title: "Regina Farmers' Market Area",
    tag: 'Local Food',
    category: 'Food',
    address: 'City Square Plaza / Downtown Regina Area',
    coordinates: {latitude: 50.4485, longitude: -104.613},
    image: images.places.farmersMarket,
    description:
      'A lively downtown market-style area connected with local food, small vendors, seasonal products, and a community-focused atmosphere when market days are active. It is a good recommendation for visitors who want to explore Regina through local flavors, small purchases, and a more casual outdoor city experience.',
    suggestedVisit: '45-90 minutes',
    bestFor: 'Local food, casual exploring, daytime visits, small shopping moments.',
    tip: 'This place works best when market activity is scheduled, so guests should check the day and time before adding it to their visit plan.',
  },
  {
    id: 'globe-theatre-area',
    title: 'Globe Theatre Area',
    tag: 'Theatre',
    category: 'Arts',
    address: '1801 Scarth Street, Regina, SK',
    coordinates: {latitude: 50.4486, longitude: -104.6129},
    image: images.places.globeTheatre,
    description:
      'A downtown cultural stop connected with live performance, theatre, arts, and Regina creative scene. Even when guests are not attending a show, the surrounding area is useful for a city guide because it sits close to restaurants, downtown walking routes, Victoria Park, and other central Regina points of interest.',
    suggestedVisit: '1-2 hours if attending a show, 20-40 minutes for area exploring',
    bestFor: 'Theatre lovers, evening plans, cultural visitors, downtown exploring.',
    tip: 'If a performance is available, this can become a strong evening pairing before or after time at the venue.',
  },
  {
    id: 'saskatchewan-science-centre',
    title: 'Saskatchewan Science Centre',
    tag: 'Family',
    category: 'Family',
    address: '2903 Powerhouse Drive, Regina, SK',
    coordinates: {latitude: 50.433, longitude: -104.5963},
    image: images.places.scienceCentre,
    description:
      'An interactive science attraction located near Wascana Centre, offering hands-on exhibits, educational displays, and a family-friendly atmosphere. It is a good choice for guests visiting Regina with children, friends, or anyone who enjoys a more active indoor experience instead of a quiet museum walk.',
    suggestedVisit: '1.5-2.5 hours',
    bestFor: 'Families, interactive exhibits, educational stops, indoor activities.',
    tip: 'This is a practical option for colder days or rainy weather, especially when guests want something engaging but not too formal.',
  },
  {
    id: 'mackenzie-art-gallery',
    title: 'MacKenzie Art Gallery',
    tag: 'Art Gallery',
    category: 'Arts',
    address: '3475 Albert Street, Regina, SK',
    coordinates: {latitude: 50.4178, longitude: -104.6172},
    image: images.places.mackenzieArtGallery,
    description:
      'A respected art destination featuring exhibitions, visual culture, and a quieter gallery atmosphere. It is suitable for guests who want a slower and more reflective stop in Regina, with enough space to enjoy art at their own pace before returning to dining, services, or evening plans.',
    suggestedVisit: '1-2 hours',
    bestFor: 'Art, quiet visits, cultural exploring, slower afternoon plans.',
    tip: 'This location pairs well with a coffee stop or a relaxed drive through the south side of Regina.',
  },
  {
    id: 'rcmp-heritage-centre',
    title: 'RCMP Heritage Centre',
    tag: 'Museum',
    category: 'Museums',
    address: '5907 Dewdney Avenue, Regina, SK',
    coordinates: {latitude: 50.4549, longitude: -104.669},
    image: images.places.rcmpHeritageCentre,
    description:
      'A major Regina heritage attraction dedicated to the history, stories, and traditions of the Royal Canadian Mounted Police. Visitors can explore exhibits, artifacts, and historical displays that present an important part of Canadian identity and Saskatchewan connection to national history.',
    suggestedVisit: '2-3 hours',
    bestFor: 'History, Canadian heritage, families, museum visitors, cultural learning.',
    tip: 'This stop is farther from the immediate downtown core than some other options, so it is better as a planned visit with transport rather than a quick walking stop.',
  },
  {
    id: 'regina-floral-conservatory',
    title: 'Regina Floral Conservatory',
    tag: 'Garden',
    category: 'Nature',
    address: '1450B 4th Avenue, Regina, SK',
    coordinates: {latitude: 50.4637, longitude: -104.6117},
    image: images.places.floralConservatory,
    description:
      'A peaceful indoor garden-style stop with seasonal plants, flowers, greenery, and a softer atmosphere. It is a pleasant option for guests who want a quiet visual break, especially during colder months when outdoor gardens may be less comfortable to visit.',
    suggestedVisit: '30-60 minutes',
    bestFor: 'Flowers, calm indoor scenery, short peaceful visits, light photography.',
    tip: 'This is a smaller stop, so it works best as part of a wider Regina route rather than the only destination of the day.',
  },
  {
    id: 'mosaic-stadium-area',
    title: 'Mosaic Stadium Area',
    tag: 'Sports Landmark',
    category: 'Sports',
    address: '1700 Elphinstone Street, Regina, SK',
    coordinates: {latitude: 50.4506, longitude: -104.6336},
    image: images.places.mosaicStadium,
    description:
      'A recognizable sports and entertainment area connected with major local events, stadium atmosphere, and larger Regina gatherings. It is a useful city-guide location for guests who are interested in sports, concerts, event nights, or a more energetic part of the city outside the central downtown area.',
    suggestedVisit: '30-90 minutes, longer during events',
    bestFor: 'Sports fans, event visitors, local atmosphere, evening entertainment.',
    tip: 'Check the event schedule before visiting, because the area feels most active when a game, concert, or large public event is taking place.',
  },
  {
    id: 'cornwall-centre',
    title: 'Cornwall Centre',
    tag: 'Shopping',
    category: 'Shopping',
    address: '2102 11th Avenue, Regina, SK',
    coordinates: {latitude: 50.4511, longitude: -104.6113},
    image: images.places.cornwallCentre,
    description:
      'A central downtown shopping destination with stores, casual food options, indoor walking space, and a convenient location close to the heart of Regina. It is a practical stop for guests who want to browse shops, pick up travel essentials, enjoy a quick snack, or spend a relaxed hour indoors before or after their visit.',
    suggestedVisit: '45 minutes - 1.5 hours',
    bestFor: 'Shopping, quick food stops, indoor breaks, downtown exploring, casual city time.',
    tip: 'This is a good option when guests want a nearby place that does not require long planning, outdoor walking, or a full afternoon schedule.',
  },
  {
    id: 'reginas-warehouse-district',
    title: "Regina's Warehouse District",
    tag: 'Local District',
    category: 'Food',
    address: '2300 Dewdney Avenue Area, Regina, SK',
    coordinates: {latitude: 50.4587, longitude: -104.6208},
    image: images.places.warehouseDistrict,
    description:
      'A character-filled district known for local businesses, restaurants, creative spaces, coffee spots, event venues, and converted warehouse-style buildings. This area gives visitors a different view of Regina beyond classic parks and museums, with a more urban and independent atmosphere.',
    suggestedVisit: '1-2 hours',
    bestFor: 'Local food, coffee stops, evening plans, independent businesses, urban exploring.',
    tip: 'Visit earlier in the evening if you want to combine food, drinks, and a short walk through the area without making the route feel rushed.',
  },
  {
    id: 'dunlop-art-gallery',
    title: 'Dunlop Art Gallery',
    tag: 'Art Gallery',
    category: 'Arts',
    address: '2311 12th Avenue, Regina, SK',
    coordinates: {latitude: 50.4486, longitude: -104.6144},
    image: images.places.dunlopArtGallery,
    description:
      'A contemporary art gallery located in the downtown Regina Public Library building, offering exhibitions, visual culture, and a quieter cultural atmosphere. It is a good stop for guests who want something thoughtful and slower-paced during their city visit.',
    suggestedVisit: '45 minutes - 1.5 hours',
    bestFor: 'Contemporary art, quiet visits, cultural breaks, downtown walking, rainy-day plans.',
    tip: 'This location is ideal for guests who want a meaningful but not overly long cultural stop before returning to dining, events, or evening activities.',
  },
  {
    id: 'saskatchewan-sports-hall-of-fame',
    title: 'Saskatchewan Sports Hall of Fame',
    tag: 'Sports Museum',
    category: 'Sports',
    address: '2205 Victoria Avenue, Regina, SK',
    coordinates: {latitude: 50.4469, longitude: -104.6127},
    image: images.places.sportsHallOfFame,
    description:
      'A downtown museum-style attraction dedicated to Saskatchewan sport history, memorable athletes, teams, achievements, and local sports culture. It is a compact but interesting stop for guests who enjoy stories of competition, community pride, historical artifacts, and regional achievement.',
    suggestedVisit: '45 minutes - 1.5 hours',
    bestFor: 'Sports fans, local history, short museum visits, families, downtown exploring.',
    tip: 'This is a strong choice for visitors who want a quick cultural stop that feels different from a traditional art gallery or nature location.',
  },
  {
    id: 'government-house',
    title: 'Government House',
    tag: 'Historic Landmark',
    category: 'Landmarks',
    address: '4607 Dewdney Avenue, Regina, SK',
    coordinates: {latitude: 50.454, longitude: -104.6477},
    image: images.places.governmentHouse,
    description:
      'A historic Regina landmark with heritage architecture, formal grounds, and a strong connection to Saskatchewan public history. The building and surrounding area offer a more classic cultural experience, making it suitable for guests who enjoy historic interiors, architecture, quiet walking space, and a slower visit outside the downtown core.',
    suggestedVisit: '1-1.5 hours',
    bestFor: 'History, architecture, heritage visits, guided-style exploring, calm cultural routes.',
    tip: 'Plan transport in advance, because this location is farther from the immediate downtown area and feels better when visited as part of a dedicated city route.',
  },
];

export const placeCategories = ['All', 'Museums', 'Landmarks', 'Nature', 'Food', 'Family'] as const;
